SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Økt;
DROP TABLE IF EXISTS Øvelse;
DROP TABLE IF EXISTS ØktHarØvelse;
DROP TABLE IF EXISTS Øvelsesgruppe;
DROP TABLE IF EXISTS Apparat;
DROP TABLE IF EXISTS ØvelseMedApparat;
DROP TABLE IF EXISTS ØvelseUtenApparat;
DROP TABLE IF EXISTS ØvelseIGruppe;

